apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-calls
  labels:
    app: load-test-calls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-calls
  template:
    metadata:
      name: load-test-calls
      labels:
        app: load-test-calls
    spec:
      containers:
        - name: load-test-calls
          image: busybox
          command:
            - /bin/sh
            - -c
            - "while true; do wget -q -O- http://php-apache; done"