apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limits
  namespace: demos
spec:
  limits:
  - type: Container
    # min:
    #   cpu: 10m    
    #   memory: 10Mi
    # max:
    #   cpu: 400m     
    #   memory: 500Mi #Maxium per Container  
    defaultRequest:
      cpu: 200m
      memory: 200Mi
    default:
      cpu: 200m   
      memory: 200Mi      